POST https://localhost:5001/api/clases HTTP/1.1
content-type: application/json

{
    "nombre": "sample",
    "nombrecss": "samplecss"
}



###
GET https://localhost:5001/api/clases HTTP/1.1




###
GET https://localhost:5001/api/productos HTTP/1.1


###
POST https://localhost:5001/api/productos HTTP/1.1
content-type: application/json

{
    "claseId": 5,
    "nombre": "sample2",
    "pesoUnd": 1,
    "peso": 25,
    "unidad": "qq",
    "bultos": 25
  }



###
DELETE https://localhost:5001/api/clases/5


###
POST https://localhost:5001/api/estibas/
content-type: application/json

{
"nivel":9,
"columna":9,
"usuariosId":16,
"paquetes":{
	"lote":"TEST3",
	"productoId":3378,
	"clienteId":36,
	"bultos":30
	}
}



###
DELETE https://localhost:5001/api/estibas/9/9

content-type: application/json
{
	"usuariosId":16
}



###
GET https://localhost:5001/api/estibas/9/9


###
GET https://localhost:5001/api/reportes/visual/2



###
PUT https://localhost:5001/api/estibas/9/9
content-type: application/json

{
"paquetes":
  {
	"bultos":17,
  "usuariosId": 16
	}
}


###
GET https://localhost:5001/api/reportes/inventario


###
GET https://localhost:5001/api/reportes/productos


###
GET https://localhost:5001/api/clases/productos HTTP/1.1


###
POST https://localhost:5001/api/estibas/multiple
content-type: application/json

{
  "ingreso":{
"nivel":1,
"columna":1,
"usuariosId":16,
"paquetes":{
	"lote":"TEST3",
	"productoId":3378,
	"clienteId":36,
	"bultos":30
	}
},
"cantidad":2}